apiVersion: v2
name: streaming-platform
description: A Helm chart for Real-Time Event Streaming Analytics Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - kafka
  - flink
  - timescale
  - redis
  - analytics
  - streaming

home: https://github.com/your-username/Real-Time-Event-Streaming-Analytics-Platform
sources:
  - https://github.com/your-username/Real-Time-Event-Streaming-Analytics-Platform

maintainers:
  - name: Platform Team
    email: platform-team@company.com

dependencies:
  - name: kafka
    version: "22.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  
  - name: redis
    version: "17.11.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  
  - name: postgresql
    version: "12.5.8"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  
  - name: prometheus
    version: "23.1.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  
  - name: grafana
    version: "6.57.4"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
